### ISSUE TITLE
Validation Error For Sector Code In Aidstream

### ISSUE THREAD

**Issue by wendyrogers** [younginnovations/aidstream-old#135]
The activity file created by Aidstream for the Abaseen Foundation ( https://www.aidstream.org/files/xml/abaseen-activities.xml) is currently failing on the IATI validator with an error for the sector code details published without the code attribute 

<sector vocabulary="6"/>

Please can you investigate to determine the cause of the problem and amend Aidstream if required.

**Comment by wendyrogers** [comment]
Also same error for

Hilfswerk Austria Zimbabwe - http://www.aidstream.org/files/xml/hwa-zm-activities.xml
Stromme - http://www.aidstream.org/files/xml/stromme_ug-activities.xml
SURF - http://www.aidstream.org/files/xml/surf-activities.xml (& 1 other error)

**Comment by anjesh** [comment]
These activities are legacy ones (from the previous IATI version where code is optional). This wouldn't happen in the newly created activities. We will be implementing the schema validation as a part of the workflow so that any existing activity which doesn't pass the schema will be up for correction. Currently these existing activities could easily leak into xml, when those problematic elements are not touched during editing. 

Followup here https://github.com/younginnovations/aidstream/issues/148
