### ISSUE TITLE
Multiple Validation Errors For Heifer

### ISSUE THREAD

**Issue by wendyrogers** [younginnovations/aidstream-old#142]
The activity file for Heifer http://www.aidstream.org/files/xml/heifer-activities.xml is currently failing on the IATI validator with a number of errors:

Element 'result': Missing child element(s). Expected is one of ( description, indicator ).
Element 'description': This element is not expected. Expected is ( title ).
Element 'period-end': This element is not expected. Expected is ( period-start ).
Element 'result': Missing child element(s). Expected is ( indicator ).
Element 'baseline': This element is not expected. Expected is ( title ).
Element 'period': This element is not expected. Expected is ( title ).

Please can you investigate and amend Aidstream as required

**Comment by rolfkleef** [comment]
I'll check in with Heifer, have been helping the person there to move forward with their publication a few weeks ago.

**Comment by wendyrogers** [comment]
Thanks Rolf that will be really helpful although you might not want to change anything until @anjesh and his team have had a look as I think most of the errors being reported are related to validation? However, have a look and see what you think?

**Comment by rolfkleef** [comment]
I saw that the activity identifier for most activities wasn't complete in the data, and had a look via AidStream.

One thing is a somewhat confusing message in their activities dashboard about the number of published activities (the actual data and the number in the Registry is 12 activities):
![2015-12-22_01](https://cloud.githubusercontent.com/assets/223935/11958485/658322ce-a8c8-11e5-8c10-c1c86548b306.png)

The IATI Identifier fields in several activities do have an organisation-specific, but somehow it seems that has not been copied to the full IATI identifier:
![2015-12-22_02](https://cloud.githubusercontent.com/assets/223935/11958562/ca96a99c-a8c8-11e5-801a-310d19f108b7.png)

There is some data missing in their AidStream records (such as result indicators) so that should have been flagged in a validation step.

**Comment by anjesh** [comment]
Same as https://github.com/younginnovations/aidstream/issues/135#issuecomment-167989277

Since we don't have schema validation, these legacy activites problematic elements don't get captured. Will be taken care after this https://github.com/younginnovations/aidstream/issues/148
