### ISSUE TITLE
Enable change of username by the admin users

### ISSUE THREAD

**Issue by anjesh** [younginnovations/aidstream-old#2]
Currently username once created can't be change. Organisations admin users should be able to change it later.

**Comment by rolfkleef** [comment]
maybe to add: too many indentifiers makes it confusing
- when you register, you're asked for an "Account identifier" that is used to construct user names
- once registered, you have under Settings a "Reporting Organisation Identifier" (with the help suggesting to use a XX-YYY-12345 format id) -- I'm not sure if this is the same as the Account Identifier above?
- there also is a Registry Publisher Id

(the same confusion happens when users create an account on the Registry: "wait, I have an organisation identifier and then another identifier here?")

from a user perspective, having "only" a short mnemonic name (eg. 'openforchange') that is the same on the Registry and in AidStream, and is the start of account names, would make it easiest.

**Comment by mesaugat** [comment]
Yes, it is quite confusing. We will make the process easier in the upcoming updates. However, organisation admin users can now change their username. (v1.2.3)
