### ISSUE TITLE
Check use of new IATI codelists

### ISSUE THREAD

**Issue by stevieflow** [younginnovations/aidstream-old#30]
Would be useful to use new format IATI codelists

@bjwebb can advise

**Comment by anjesh** [comment]
Few codes are missing from codelists. 

Conditions/condition/@type - add '3 Fiduciary' http://iatistandard.org/codelists/ConditionType/
Flow-type/@code in both default-flow-type and transaction - add '40 Non flow eg GNI http://iatistandard.org/codelists/FlowType/ 
Collaboration-type/@code - see #53 
Contact-info/@type - see #49 (will be fixed in 1.2.9)

Also need to check the help-text.

**Comment by mesaugat** [comment]
Missing codelists are now included in v1.2.8
Help text updated.
closes #53
